### ISSUE TITLE
iTunes 12.4 compatibility

### ISSUE THREAD

**Issue by wincent** [wincent/synergy#1]
Multiple reports received:
#1

> Immediately after the last OSX security patch install for Yosemite a couple days back, Synergy's pop-up display started coming up empty outside of little blob containing zero characters (screen shot attached). I searched for a place to state this at GitHub but could not find it. Pardon the direct email.

![unnamed](https://cloud.githubusercontent.com/assets/7074/15370968/28589038-1cee-11e6-9322-b5939272f036.jpg)
#2

> Are you planning on releasing version which is compatible with the new version of iTunes released yesterday? In happy user of your program thinks it’s very beginning you released it
#3

> I’ve been a user of Synergy for quite some time, and have thoroughly enjoyed your product. However, I’m not able to get it to work on OS X Yosemite. I’m wondering if it is no longer supported on Yosemite or El Capitan?
#4

> Since the iTunes update 2-3 days ago, the Synergy floater says that iTunes hasn’t started and I can’t seem to get it to recognize that iTunes is actually running.
#5

> Does Synergy work with iTunes 12.4?
#6

> Synergy doesn't work fine on iTunes 12.4.

**Comment by wincent** [comment]
Synergy went open source in February 2012:

https://wincent.com/blog/synergy-open-source-release

And went free in May 2014:

https://wincent.com/blog/synergy-6.0a-release

I'm not actively working on it any more, but am happy to accept pull requests if anybody runs into an issue and wants to fix it.

The other possibility with this specific issue is that Apple may fix it with a point release to iTunes. This kind of thing has happened before.

**Comment by kemar** [comment]
I really enjoyed Synergy since many years but I guess it's time to find an alternative :'(

**Comment by sbliven** [comment]
Wow, it's really a tribute that Synergy has been bug free and feature full for four years now. I really hope someone (maybe me) finds the time to debug this.

**Comment by beporter** [comment]
I just updated to iTunes 12.5.1.21 (On OS X 10.9.5 13F1911) and the Synergy floater seems to be (miraculously) working again. Maybe this bug was actually on Apple's end this whole time?

**Comment by shepster** [comment]
I also noticed the floater is back. iTunes 12.5.1.21, OS X 10.11.6

**Comment by wincent** [comment]
> Maybe this bug was actually on Apple's end this whole time?

Of course it was. (With rare exceptions) 13-year-old code doesn't suddenly stop working due to a hitherto undiscovered bug. There have been several examples of shit breaking in Synergy due to an iTunes update, and later getting unbroken by a new update. As I said above:

> The other possibility with this specific issue is that Apple may fix it with a point release to iTunes. This kind of thing has happened before.

In any case, thanks for reporting your findings!
