### ISSUE TITLE
Missing com.wincent.buildtools.gitrev.h

### ISSUE THREAD

**Issue by sbliven** [wincent/synergy#4]
The code seems to expect com.wincent.buildtools.gitrev.h to get populated. Maybe this used to work via a git hook or something, but it is causing build errors with github. I was able to find reference to a WO_BUILDNUMBER macro from this file, so I could work around the problem with the following command:

```
echo "#define WO_BUILDNUMBER $(git rev-list HEAD)" > com.wincent.buildtools.gitrev.h
```

Are there any other macros that need to be defined in this header?

**Comment by sbliven** [comment]
I found a few more:

``` bash
echo "#define WO_BUILDNUMBER \"$(git rev-parse HEAD)\"" > com.wincent.buildtools.gitrev.h
echo "#define WO_BUILDNUMBER_STRING \"$(git rev-parse --abbrev-ref HEAD)\"" >> com.wincent.buildtools.gitrev.h
echo "#define WO_BUILDDATE \"$(date "+%Y-%m-%d")\"" >> com.wincent.buildtools.gitrev.h
```

**Comment by wincent** [comment]
> Maybe this used to work via a git hook or something

From memory, it was a shell script build step invoked by Xcode, but my memory may be failing me (it's about 4 years since I last built this project). None of this was intended to be manual, but things may have gotten broken due to time/bit-rot/entropy.

**Comment by sbliven** [comment]
You're absolutely right. It's generated by the `update build number` target in Xcode, which runs `buildtools/UpdateGitRevisionNumbers.rb`.
