### ISSUE TITLE
Update Xcode project

### ISSUE THREAD

**Issue by sbliven** [wincent/synergy#5]
The xcode project needs a number of updates to build with XCode 7 on OSX 10.11. I don't have the project fully compiling yet, but here are some changes I've had to make so far:
1. Updated SDK on all targets
2. Delete missing files from `SynergyApp/Other Sources`
3. Disable garbage collection (set GC_ENABLE_OBJC_GC=NO for all targets). This may introduce massive memory leaks.

I'm currently down to a problem running PreprocessInfoPlistStrings.sh, so hopefully I'm nearing the end!

**Comment by wincent** [comment]
Yeah, the bit-rot... All of this stuff used to work, but this is the way of things, I think. Thanks for trying to sort it out.

**Comment by sbliven** [comment]
Issues aren't open for buildtools, so I'll just continue this issue. It looks like the script `wincent-strings-util` should be included with buildtools but isn't:

```
buildtools/PreprocessInfoPlistStrings.sh: line 85: wincent-strings-util: command not found
```

**Comment by wincent** [comment]
You need the tool in your path. You can get it from [here](http://www.wincent.com/a/products/wincent-strings-util/).

Also, I'll enable issues on the other repos.
