### ISSUE TITLE
Missing WOSysctl.c

### ISSUE THREAD

**Issue by revmischa** [wincent/synergy#6]
Says it's missing SynergyApp/Other Sources/WOSysctl.c
Any chance you can add a built version of the latest src under "Releases" on github?

**Comment by beporter** [comment]
I believe that file is available in another one of the wincent repos, here: https://github.com/wincent/WOPublic/blob/master/WOSysctl.m 

I was able to copy it into the correct place and proceed, but got bogged down trying to update the xCode project from GC to ARC. I never got the project to successfully build. 😞

**Comment by wincent** [comment]
> I believe that file is available in another one of the wincent repos, here: https://github.com/wincent/WOPublic/blob/master/WOSysctl.m

That's right, in a submodule, which you should have gotten if you cloned with `git clone --recursive`, or you can check it out after the fact with `git submodule update --init`.
